# Setup
title:               电力经济学十讲
tagline:             ''
description:         '电力经济学十讲'
url:                 https://yingzheng-econ.github.io/Econ_Power_Market/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              郑𬎆
  url:
  email:             yingzheng@ruc.edu.cn

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: 
